# This file contains configuration options for GolangCI-Lint.
#
# - It requires golangci-lint 1.48.0 or newer.
# - Available linters see: https://golangci-lint.run/usage/linters/
# - Sample of config see: https://golangci-lint.run/usage/configuration/#config-file

# Options for analysis running
run:
  # Include test files.
  tests: true
  # Fail fast.
  fast: true

  # List of build tags, all linters use it. Default is empty list.
  build-tags:
    - golangci

  # Which dirs to skip. Issues from them won't be reported.
  skip-dirs:
    - .github

  # Allow multiple parallel golangci-lint instances running.
  allow-parallel-runners: true

# Output configuration options
output:
  format: colored-line-number

  # Sorts results by: filepath, line and column
  sort-results: true

# Enabled all linters. Conf settings may follow.
linters:
  enable-all: true
  disable:
  # Disable deprecated/abandoned linters
  - nosnakecase
  - scopelint
  - golint
  - deadcode
  - interfacer
  - varcheck
  - exhaustivestruct
  - ifshort
  - maligned
  - structcheck
  # Disabled because of testing private functions
  - testpackage
  # We allow global variable for testing purposes
  - gochecknoglobals
  # Disabled due to the use of external packages
  - depguard
