version: "2"
run:
  tests: true
  allow-parallel-runners: true

linters:
  default: all
  disable:
    # Deprecated linters
    - wsl
    - gomodguard
    # Disable due to the external dependency
    - depguard
    # Disable to test private functions
    - testpackage
    # Allow global variables
    - gochecknoglobals
  settings:
    paralleltest:
      ignore-missing: false
    varnamelen:
      ignore-names:
        - ok
        - t
        - tt
